services:

  auth-service:
    image: auth-service
    build:
      context: .
    ports:
      - "8091:8091"

    environment:
      SPRING_REDIS_HOST: my-redis
      SPRING_REDIS_PORT: 6379
      PASSWORD: nul
      TIMEOUT: 2000
      SPRING_DATASOURCE_URL: jdbc:postgresql://79.174.80.223:5432/auth_user_db
      SPRING_DATASOURCE_USERNAME: login_for_your_db
      SPRING_DATASOURCE_PASSWORD: password_for_your_db
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 79.174.80.223:9092
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
    networks:
      - kafka-docker_kafka-net
      - microservice-network
      - teamcity_default

networks:
  kafka-docker_kafka-net:
    external: true
  microservice-network:
    external: true
  teamcity_default:
    external: true
