spring:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_user_db
    username: root
    password: root
    hikari:
      schema: public
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS user_schema
      connection-timeout: 10000

app:
  jwt:
    secret: "someSecretKey"
    tokenExpiration: 3m
    refreshTokenExpiration: 15m


logging:
  level:
    org:
      springframework:
        orm:
          jpa:
            INFO
          JpaTransactionManager:
            DEBUG
        transaction:
          INFO
        interceptor:
          TRACE


