CREATE TABLE IF NOT EXISTS users (
                                     id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     uuid              VARCHAR(320) NOT NULL UNIQUE,
                                     deleted           BOOLEAN NOT NULL,
                                     blocked           BOOLEAN NOT NULL,
                                     first_name        VARCHAR(320) NOT NULL,
                                     last_name         VARCHAR(320) NOT NULL,
                                     email             VARCHAR(320) NOT NULL UNIQUE,
                                     password1          VARCHAR(3200) NOT NULL UNIQUE,
                                     password2         VARCHAR(3200) NOT NULL UNIQUE,
                                     message_permission VARCHAR(320)
);

CREATE TABLE user_roles (
                            user_id         BIGINT NOT NULL,
                            roles           VARCHAR(255) NOT NULL CHECK (roles IN ('USER','ADMIN')),

                            CONSTRAINT fk_user_roles_on_user
                                FOREIGN KEY (user_id) REFERENCES users (id)
);