CREATE TABLE IF NOT EXISTS users (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid              VARCHAR(32) NOT NULL UNIQUE,
  deleted        BOOLEAN NOT NULL,
  first_name        VARCHAR(32) NOT NULL,
  last_name         VARCHAR(32) NOT NULL,
  email             VARCHAR(32) NOT NULL UNIQUE,
  password          VARCHAR(320) NOT NULL UNIQUE,
  password2         VARCHAR(320) NOT NULL UNIQUE,
  blocked           BOOLEAN,
  message_permission VARCHAR(320)
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id         BIGINT NOT NULL,
    roles           VARCHAR(255) CHECK (roles IN ('USER','ADMIN')),

    CONSTRAINT fk_user_roles_on_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);